import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';
import GuestLayout from '@/Layouts/GuestLayout';
import { Head, useForm } from '@inertiajs/react';
import { useRef, useState } from 'react';

export default function TwoFactorChallenge() {
    const [recovery, setRecovery] = useState(false);
    const codeInput = useRef();
    const recoveryCodeInput = useRef();

    const form = useForm({
        code: '',
        recovery_code: '',
    });

    const toggleRecovery = () => {
        setRecovery((current) => !current);

        window.setTimeout(() => {
            if (recovery) {
                codeInput.current?.focus();
                form.setData('recovery_code', '');
            } else {
                recoveryCodeInput.current?.focus();
                form.setData('code', '');
            }
        }, 0);
    };

    const submit = (event) => {
        event.preventDefault();

        form.post(route('two-factor.login'), {
            onFinish: () => form.reset('code', 'recovery_code'),
        });
    };

    return (
        <GuestLayout>
            <Head title="Two-Factor Challenge" />

            <div className="flex min-h-screen items-center justify-center bg-[#efefef] px-4">
                <div className="w-full max-w-md rounded-lg bg-white p-8 shadow-sm">
                    <h1 className="text-2xl font-black tracking-tight text-slate-800">
                        Two-Factor Authentication
                    </h1>

                    <p className="mt-2 text-sm text-slate-600">
                        {recovery
                            ? 'Enter one of your emergency recovery codes to access your account.'
                            : 'Enter the authentication code generated by your authenticator app.'}
                    </p>

                    <form onSubmit={submit} className="mt-6 space-y-5">
                        {!recovery ? (
                            <div>
                                <InputLabel htmlFor="code" value="Authentication code" />
                                <TextInput
                                    id="code"
                                    ref={codeInput}
                                    value={form.data.code}
                                    onChange={(event) => form.setData('code', event.target.value)}
                                    type="text"
                                    inputMode="numeric"
                                    autoComplete="one-time-code"
                                    className="mt-1 block w-full"
                                    isFocused
                                />
                                <InputError message={form.errors.code} className="mt-2" />
                            </div>
                        ) : (
                            <div>
                                <InputLabel htmlFor="recovery_code" value="Recovery code" />
                                <TextInput
                                    id="recovery_code"
                                    ref={recoveryCodeInput}
                                    value={form.data.recovery_code}
                                    onChange={(event) => form.setData('recovery_code', event.target.value)}
                                    type="text"
                                    autoComplete="one-time-code"
                                    className="mt-1 block w-full"
                                />
                                <InputError message={form.errors.recovery_code} className="mt-2" />
                            </div>
                        )}

                        <div className="flex items-center justify-between">
                            <button
                                type="button"
                                onClick={toggleRecovery}
                                className="text-sm font-semibold text-indigo-600 hover:text-indigo-800"
                            >
                                {recovery ? 'Use an authenticator code' : 'Use a recovery code'}
                            </button>

                            <PrimaryButton disabled={form.processing}>
                                Log in
                            </PrimaryButton>
                        </div>
                    </form>
                </div>
            </div>
        </GuestLayout>
    );
}
